import { Link } from 'react-router-dom'
import styled from 'styled-components'

const projects = [
  ['01', 'Original IP', 'Worlds worth wandering into', 'We build character-led worlds, designed to stay with players long after the credits.', 'coral'],
  ['02', 'Co-development', 'Extra paws for bold teams', 'Art, TechArt and programming support that fits naturally into your production.', 'mint'],
  ['03', 'In the workshop', 'Something curious is brewing', 'A glimpse of the experiments, sketches and prototypes currently keeping us busy.', 'sun'],
] as const
const Page = styled.div`overflow:hidden;`
const Hero = styled.section`min-height:calc(100vh - 82px); padding:clamp(42px,7vw,100px) clamp(24px,6vw,84px) 42px; position:relative; display:grid; align-items:end; isolation:isolate; background:var(--ink); color:var(--paper); &::before{content:'';position:absolute;width:min(58vw,800px);aspect-ratio:1;border-radius:50%;background:var(--coral);right:-12%;top:-34%;z-index:-1;} &::after{content:'';position:absolute;width:min(42vw,540px);aspect-ratio:1;border-radius:42% 58% 52% 48%;background:var(--mint);left:-12%;bottom:-26%;z-index:-1;}`
const HeroGrid = styled.div`display:grid; grid-template-columns:minmax(0,1.35fr) minmax(260px,.65fr); gap:40px; max-width:1360px; width:100%; margin:0 auto; @media(max-width:760px){grid-template-columns:1fr;}`
const Kicker = styled.p`margin:0 0 23px; font-size:11px; letter-spacing:.17em; text-transform:uppercase; font-weight:800; color:rgba(255,253,248,.7);`
const HeroTitle = styled.h1`max-width:900px;margin:0;font-size:clamp(62px,10.4vw,154px);letter-spacing:-.085em;line-height:.78;text-transform:uppercase;span{display:block;color:var(--coral);}`
const HeroSide = styled.div`align-self:end;border-left:1px solid rgba(255,253,248,.35);padding:0 0 5px 26px;p{margin:0 0 28px;max-width:350px;font-size:clamp(18px,2vw,25px);line-height:1.18;letter-spacing:-.03em;}@media(max-width:760px){border-left:0;border-top:1px solid rgba(255,253,248,.35);padding:24px 0 0;}`
const Actions = styled.div`display:flex;flex-wrap:wrap;gap:12px;a{display:inline-flex;padding:14px 18px;border:1px solid var(--paper);border-radius:999px;text-decoration:none;text-transform:uppercase;letter-spacing:.11em;font-weight:800;font-size:10px;}a:first-child{background:var(--paper);color:var(--ink);}a:hover{background:var(--coral);border-color:var(--coral);color:var(--ink);}`
const Marquee = styled.div`overflow:hidden;border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:15px 0;background:var(--paper);div{white-space:nowrap;width:max-content;font-size:12px;text-transform:uppercase;font-weight:850;letter-spacing:.15em;animation:move 26s linear infinite;}@keyframes move{to{transform:translateX(-25%);}}`
const Section = styled.section`max-width:1360px;margin:0 auto;padding:clamp(76px,12vw,170px) clamp(24px,6vw,84px);`
const Heading = styled.div`display:flex;justify-content:space-between;align-items:end;gap:24px;margin-bottom:clamp(34px,6vw,70px);p{margin:0;text-transform:uppercase;letter-spacing:.15em;font-size:11px;font-weight:850;}h2{max-width:740px;margin:0;text-transform:uppercase;letter-spacing:-.07em;line-height:.82;font-size:clamp(48px,8vw,106px);}@media(max-width:660px){display:block;p{margin-bottom:20px;}}`
const Grid = styled.div`display:grid;grid-template-columns:repeat(3,1fr);gap:16px;@media(max-width:840px){grid-template-columns:1fr;}`
const Project = styled.article<{ $tone:string }>`min-height:465px;padding:25px;display:flex;flex-direction:column;justify-content:space-between;border-radius:4px;color:var(--ink);background:${({$tone})=>$tone==='coral'?'var(--coral)':$tone==='mint'?'var(--mint)':'var(--sun)'};.top{display:flex;justify-content:space-between;text-transform:uppercase;font-size:10px;letter-spacing:.13em;font-weight:850;}.shape{width:58%;aspect-ratio:1;align-self:center;background:var(--ink);border-radius:${({$tone})=>$tone==='coral'?'50% 50% 8% 50%':$tone==='mint'?'50% 8% 50% 50%':'12% 50% 50% 50%'};transform:rotate(-12deg);opacity:.92;}h3{max-width:330px;margin:0 0 13px;font-size:clamp(31px,3vw,47px);line-height:.88;letter-spacing:-.06em;text-transform:uppercase;}p{max-width:300px;margin:0;line-height:1.4;font-size:15px;}`
const Reel = styled.section`padding:clamp(80px,12vw,160px) clamp(24px,6vw,84px);background:var(--paper);div{max-width:1080px;margin:0 auto;}h2{margin:0 0 30px;font-size:clamp(46px,7vw,90px);letter-spacing:-.07em;line-height:.8;text-transform:uppercase;}.tablet{padding:clamp(10px,1.25vw,16px);aspect-ratio:16/10;background:var(--ink);border-radius:clamp(22px,3vw,38px);box-shadow:0 35px 80px rgba(60,52,41,.21);}.screen{height:100%;border-radius:clamp(14px,2vw,25px);overflow:hidden;background:var(--sand);position:relative;}video{width:100%;height:100%;object-fit:cover;}.placeholder{position:absolute;inset:0;display:grid;place-items:center;pointer-events:none;span{padding:11px 17px;border:1px solid rgba(37,35,31,.22);border-radius:999px;background:rgba(255,253,248,.7);font-size:10px;text-transform:uppercase;letter-spacing:.14em;font-weight:850;}}`
const Statement = styled.section`padding:clamp(80px,12vw,170px) clamp(24px,6vw,84px);background:var(--ink);color:var(--paper);div{max-width:1360px;margin:0 auto;}p{max-width:1040px;margin:0;font-size:clamp(32px,5.1vw,76px);letter-spacing:-.06em;line-height:.95;}strong{color:var(--coral);font-weight:inherit;}`
const Services = styled.section`max-width:1360px;margin:0 auto;padding:clamp(80px,12vw,160px) clamp(24px,6vw,84px);display:grid;grid-template-columns:.75fr 1.25fr;gap:40px;h2{margin:0;font-size:clamp(46px,7vw,96px);line-height:.82;letter-spacing:-.07em;text-transform:uppercase;}@media(max-width:720px){grid-template-columns:1fr;}`
const List = styled.div`border-top:1px solid var(--line);div{display:grid;grid-template-columns:58px 1fr auto;gap:18px;align-items:center;padding:21px 0;border-bottom:1px solid var(--line);}span,b{font-size:11px;text-transform:uppercase;letter-spacing:.12em;}b{font-size:clamp(19px,2.5vw,31px);letter-spacing:-.04em;}i{font-style:normal;font-size:20px;}`
const Band = styled.section`padding:clamp(60px,9vw,120px) clamp(24px,6vw,84px);background:var(--mint);div{max-width:1360px;margin:0 auto;display:flex;align-items:end;justify-content:space-between;gap:34px;}h2{max-width:870px;margin:0;font-size:clamp(48px,8vw,112px);letter-spacing:-.08em;line-height:.78;text-transform:uppercase;}a{flex:none;border-radius:999px;padding:18px 24px;background:var(--ink);color:var(--paper);font-size:11px;font-weight:850;letter-spacing:.13em;text-transform:uppercase;text-decoration:none;}@media(max-width:620px){div{display:block;}a{display:inline-block;margin-top:28px;}}`
export function Home(){return <Page><Hero><HeroGrid><div><Kicker>Raccoons at Work Studios · Est. 2024</Kicker><HeroTitle>Making games with <span>curious paws.</span></HeroTitle></div><HeroSide><p>An indie game-dev cooperative creating original worlds and lending sharp, reliable support to fellow indie teams.</p><Actions><Link to="/about-us">Meet the cooperative ↗</Link><Link to="/contact">Work with us ↗</Link></Actions></HeroSide></HeroGrid></Hero><Marquee><div>Original IPs ✦ Art ✦ TechArt ✦ Programming ✦ Co-development ✦ Original IPs ✦ Art ✦ TechArt ✦ Programming ✦ Co-development ✦</div></Marquee><Section><Heading><p>01 — What we make</p><h2>Small team. Big worlds.</h2></Heading><Grid>{projects.map(([number,type,title,copy,tone])=><Project key={number} $tone={tone}><div className="top"><span>{number}</span><span>{type}</span></div><div className="shape" aria-hidden="true"/><div><h3>{title}</h3><p>{copy}</p></div></Project>)}</Grid></Section><Reel><div><h2>Our showreel.</h2><div className="tablet"><div className="screen"><video controls preload="metadata" aria-label="Raccoons at Work Studios showreel"><source src="/videos/showreel.mp4" type="video/mp4"/>Your browser does not support HTML video.</video><div className="placeholder"><span>Showreel · video coming soon</span></div></div></div></div></Reel><Statement><div><p>We believe the best games feel <strong>specific, human and a little unexpected.</strong> That is why we make them together.</p></div></Statement><Services><h2>Bring us into your world.</h2><List>{['Visual development & art','TechArt & pipelines','Gameplay & tools programming','Co-development'].map((service,index)=><div key={service}><span>0{index+1}</span><b>{service}</b><i>↗</i></div>)}</List></Services><Band><div><h2>Have a world in mind?</h2><Link to="/contact">Start a conversation ↗</Link></div></Band></Page>}
